### ISSUE TITLE
Investigate why modelgauge test runs fail

### ISSUE THREAD

**Issue by rogthefrog** [mlcommons/modelgauge#506]
https://github.com/mlcommons/modelgauge/actions/runs/10341862847/job/28624140017

**Comment by rogthefrog** [comment]
There are two "fixes":

* one clears storage so the test doesn't run out of space on the device
* the other installs modelgauge as a package locally from the code that is checked out in the runner, rather than pypi, and tests whether all the tests can be loaded. 

The first fix is fairly non-controversial :)

 The second fix requires a conversation with @wpietri to clarify the goal of this particular test.

**Comment by wpietri** [comment]
I think back in the day this was to make sure that our released artifact continued to work. I suspect that's still a good thing to do, but let's discuss in stand-up a) whether this is the right test for that, b) there's a better way to keep the version tested in sync, and c) whether what this tests is also covered during our pull-request tests.

**Comment by rogthefrog** [comment]
The initial goal is to make sure the published Pypi package still works (not the local version).

**Comment by rogthefrog** [comment]
The last (hopefully) thing we need is an environment secret in the github workflow named `PERSPECTIVE_API_KEY` set to our perspective API key. @wpietri or @bollacker is that something you can add? Other than that I think this is good to go.

**Comment by rogthefrog** [comment]
OK I think this is good to go @wpietri
