### ISSUE TITLE
Update dependency versions to allow installing the new ensemble annotator package from modeltune without version conflicts

### ISSUE THREAD

**Issue by bkorycki** [mlcommons/modelgauge#527]

**Comment by rogthefrog** [comment]
Ready @bkorycki

**Comment by rogthefrog** [comment]
After conversations this week, I've updated the title of this card to reflect our intent, and reduced the scope accordingly, with this PR implementing the goal we agreed to.

https://github.com/mlcommons/modelgauge/pull/538
